
name: Second workflow
on: push
jobs: 
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: "welcome"
        run: echo "welcome to the code step by step"
  
  Bye-job:
    runs-on: ubuntu-latest
    steps:
      - name: "Bye"
        run: echo "Bye code step by step"

  

